# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/sample.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'grpc/sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc/sample.proto\x12\x07matches\"H\n\x13MatchesListResponse\x12\x31\n\x07results\x18\x01 \x03(\x0b\x32 .matches.MatchesRetrieveResponse\"\x1d\n\x0fRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x17MatchesRetrieveResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x32]\n\x11MatchesController\x12H\n\x08Retrieve\x12\x18.matches.RetrieveRequest\x1a .matches.MatchesRetrieveResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHESLISTRESPONSE']._serialized_start=30
  _globals['_MATCHESLISTRESPONSE']._serialized_end=102
  _globals['_RETRIEVEREQUEST']._serialized_start=104
  _globals['_RETRIEVEREQUEST']._serialized_end=133
  _globals['_MATCHESRETRIEVERESPONSE']._serialized_start=135
  _globals['_MATCHESRETRIEVERESPONSE']._serialized_end=172
  _globals['_MATCHESCONTROLLER']._serialized_start=174
  _globals['_MATCHESCONTROLLER']._serialized_end=267
# @@protoc_insertion_point(module_scope)
